### ISSUE TITLE
Run arm_vexpress_a9 with QEMU

### ISSUE THREAD

**Issue by nguyenhien1994** [hhdang6637/embedded_linux_skeleton#14]
**Description.**
Currently, we cannot use QEMU to test the arm_vexpress_a9 model after it was integrated into `master` branch. So we need to change some code to build and run the test with QEMU.

**Solution**
We should make a Virtual FAT file system that contains an u-boot script and ITB so that QEMU can run as the SD card.

**Addition**
The apps must be included in this image.

**Comment by hhdang6637** [comment]
Hi @nguyenhien1994 and @quoctri1 ,
Please see https://github.com/hhdang6637/embedded_linux_skeleton/wiki/raspberry-pi-sd-card-layout to make sure you understand the partition layout of SD card.

**Comment by hhdang6637** [comment]
@nguyenhien1994 , we can start qemu now.

Please see commit https://github.com/hhdang6637/embedded_linux_skeleton/commit/9ca5f4eca876e80302241897527500cb09b61aa4
