### ISSUE TITLE
Move Dropbear from Buildroot to applications to let us can control it more easier.

### ISSUE THREAD

**Issue by hhdang6637** [hhdang6637/embedded_linux_skeleton#18]
**Is your feature request related to a problem? Please describe.**
Currently, Dropbear is take cared by buildroot. We need move it to applications.

**Comment by tranconghau** [comment]
Sorry. What do you mean about “your feature reuqest”? I don’t remember that feature, please help to explain it.

I will take care of this issue soon.

**Comment by hhdang6637** [comment]
@
