### ISSUE TITLE
we need small library to read/write ini config file

### ISSUE THREAD

**Issue by hhdang6637** [hhdang6637/embedded_linux_skeleton#46]
We're going to let user set up some things, we need store user configuration.

**Comment by hhdang6637** [comment]
@quoctri1 , do you know ini config file?

**Comment by quoctri1** [comment]
No, I'm not

**Comment by hhdang6637** [comment]
This is an example.

`
; Test config file for ini_example.c and INIReaderTest.cpp

[protocol]             ; Protocol configuration
version=6              ; IPv6

[user]
name = Bob Smith       ; Spaces around '=' are stripped
email = bob@smith.com  ; And comments (like this) ignored
active = true          ; Test a boolean
pi = 3.14159           ; Test a floating point number
multi = this is a      ; test
        multi-line value ; test

`

**Comment by hhdang6637** [comment]
thanks @tranconghau  for working on this
